// locations.js

export const FLORIDA_LOCATIONS = [
  // ─── ✈️ AEROPUERTOS COMERCIALES Y FBO (EJECUTIVOS) ───
  { id: 'MIA', name: 'Miami International Airport (MIA)', lat: 25.7959, lng: -80.2870, type: 'airport', tags: 'aeropuerto aereopuerto vuelo flight avion terminal fbo comercial' },
  { id: 'FLL', name: 'Fort Lauderdale-Hollywood Airport (FLL)', lat: 26.0722, lng: -80.1527, type: 'airport', tags: 'aeropuerto aereopuerto vuelo flight avion terminal fbo comercial' },
  { id: 'PBI', name: 'Palm Beach International Airport (PBI)', lat: 26.6831, lng: -80.0956, type: 'airport', tags: 'aeropuerto aereopuerto vuelo flight avion terminal fbo comercial' },
  { id: 'OPF', name: 'Miami Opa-Locka Executive Airport (VIP FBO)', lat: 25.9070, lng: -80.2783, type: 'airport', tags: 'aeropuerto aereopuerto vuelo flight avion terminal fbo vip privado jet opaloca opaloka' },
  { id: 'TMB', name: 'Miami Executive Airport - Kendall', lat: 25.6480, lng: -80.4328, type: 'airport', tags: 'aeropuerto aereopuerto vuelo flight avion terminal fbo vip privado jet tamiami' },
  { id: 'FXE', name: 'Fort Lauderdale Executive Airport', lat: 26.1973, lng: -80.1707, type: 'airport', tags: 'aeropuerto aereopuerto vuelo flight avion terminal fbo vip privado jet' },
  { id: 'BCT', name: 'Boca Raton Airport (FBO)', lat: 26.3783, lng: -80.1076, type: 'airport', tags: 'aeropuerto aereopuerto vuelo flight avion terminal fbo vip privado jet voca' },
  { id: 'APF', name: 'Naples Airport (Executive)', lat: 26.1525, lng: -81.7752, type: 'airport', tags: 'aeropuerto aereopuerto vuelo flight avion terminal fbo vip privado jet napoles' },
  { id: 'X44', name: 'Miami Seaplane Base', lat: 25.7833, lng: -80.1777, type: 'airport', tags: 'aeropuerto aereopuerto hidroavion seaplane agua watson' },
  { id: 'ORC', name: 'Ocean Reef Club Airport (Private)', lat: 25.3242, lng: -80.2755, type: 'airport', tags: 'aeropuerto aereopuerto vuelo flight avion terminal fbo vip privado jet cayo largo reef' },
  { id: 'ORL', name: 'Orlando Executive Airport (FBO)', lat: 28.5455, lng: -81.3329, type: 'airport', tags: 'aeropuerto aereopuerto vuelo flight avion terminal fbo vip privado jet orlando' },
  { id: 'ISM', name: 'Kissimmee Gateway Airport (FBO Disney)', lat: 28.2898, lng: -81.4371, type: 'airport', tags: 'aeropuerto aereopuerto vuelo flight avion terminal fbo vip privado jet orlando disney' },
  { id: 'SUA', name: 'Witham Field Stuart (FBO)', lat: 27.1824, lng: -80.2223, type: 'airport', tags: 'aeropuerto aereopuerto vuelo flight avion terminal fbo vip privado jet stuart wpb' },

  // ─── 🛳️ PUERTOS Y MARINAS VIP ───
  { id: 'PORT_MIA', name: 'PortMiami (Terminal de Cruceros)', lat: 25.7781, lng: -80.1750, type: 'port', tags: 'puerto port marina barco crucero yate cruise yacht terminal royal caribbean msc' },
  { id: 'PORT_EVG', name: 'Port Everglades (Cruceros FTL)', lat: 26.0858, lng: -80.1170, type: 'port', tags: 'puerto port marina barco crucero yate cruise yacht terminal' },
  { id: 'PORT_PB', name: 'Port of Palm Beach', lat: 26.7667, lng: -80.0528, type: 'port', tags: 'puerto port marina barco crucero yate cruise yacht terminal' },
  { id: 'MARINA_MIA', name: 'Miami Beach Marina', lat: 25.7711, lng: -80.1388, type: 'port', tags: 'puerto port marina barco crucero yate cruise yacht amarre' },
  { id: 'MARINA_SUNNY', name: 'Sunny Isles Beach Marina', lat: 25.9320, lng: -80.1264, type: 'port', tags: 'puerto port marina barco crucero yate cruise yacht amarre' },
  { id: 'MARINA_COCO', name: 'Dinner Key Marina (Coconut Grove)', lat: 25.7281, lng: -80.2372, type: 'port', tags: 'puerto port marina barco crucero yate cruise yacht amarre' },
  { id: 'MARINA_AUBERGE', name: 'Auberge Beach Marina FTL', lat: 26.1550, lng: -80.0980, type: 'port', tags: 'puerto port marina barco crucero yate cruise yacht amarre' },
  { id: 'MARINA_RYBOVICH', name: 'Safe Harbor Rybovich (WPB)', lat: 26.7371, lng: -80.0489, type: 'port', tags: 'puerto port marina barco crucero yate cruise yacht amarre superyate' },
  { id: 'MARINA_FISHER', name: 'Fisher Island Club Marina', lat: 25.7611, lng: -80.1411, type: 'port', tags: 'puerto port marina barco crucero yate cruise yacht amarre privada' },
  { id: 'MARINA_HAULOVER', name: 'Haulover Marina', lat: 25.9038, lng: -80.1233, type: 'port', tags: 'puerto port marina barco crucero yate cruise yacht amarre' },
  { id: 'MARINA_TURNBERRY', name: 'Turnberry Isle Marina', lat: 25.9535, lng: -80.1288, type: 'port', tags: 'puerto port marina barco crucero yate cruise yacht amarre' },
  { id: 'MARINA_PIER66', name: 'Pier 66 Marina (FTL)', lat: 26.1023, lng: -80.1175, type: 'port', tags: 'puerto port marina barco crucero yate cruise yacht amarre superyate' },
  { id: 'MARINA_BAHIAMAR', name: 'Bahia Mar Yachting Center (FTL)', lat: 26.1118, lng: -80.1064, type: 'port', tags: 'puerto port marina barco crucero yate cruise yacht amarre boat show' },

  // ─── 🏟️ ESTADIOS, ARENAS Y ENTRETENIMIENTO ───
  { id: 'ST_NU', name: 'Nu Stadium - Inter Miami CF (Miami Freedom Park)', lat: 25.7931, lng: -80.2590, type: 'stadium', tags: 'estadio cancha partido futbol nfl mundial soccer arena messi' },
  { id: 'ST_HARDROCK', name: 'Hard Rock Stadium (Dolphins / F1)', lat: 25.9580, lng: -80.2389, type: 'stadium', tags: 'estadio cancha partido futbol nfl mundial soccer arena recital concierto formula' },
  { id: 'ST_CHASE', name: 'Chase Stadium (Inter Miami FTL)', lat: 26.1936, lng: -80.1606, type: 'stadium', tags: 'estadio cancha partido futbol nfl mundial soccer arena messi' },
  { id: 'ST_KASEYA', name: 'Kaseya Center (Miami Heat)', lat: 25.7814, lng: -80.1870, type: 'stadium', tags: 'estadio cancha partido basket nba basketball arena recital concierto ftx' },
  { id: 'ST_LOANDEPOT', name: 'LoanDepot Park (Miami Marlins)', lat: 25.7783, lng: -80.2196, type: 'stadium', tags: 'estadio cancha partido beisbol baseball mlb arena marlins park' },
  { id: 'ST_AMERANT', name: 'Amerant Bank Arena (Florida Panthers)', lat: 26.1569, lng: -80.3256, type: 'stadium', tags: 'estadio cancha partido hockey nhl hielo arena recital concierto' },
  { id: 'ST_FIU', name: 'FIU Stadium', lat: 25.7525, lng: -80.3778, type: 'stadium', tags: 'estadio cancha partido futbol nfl soccer arena universitario' },
  { id: 'ST_FAU', name: 'FAU Stadium (Boca Raton)', lat: 26.3762, lng: -80.1018, type: 'stadium', tags: 'estadio cancha partido futbol nfl soccer arena universitario voca' },
  { id: 'ST_GULFSTREAM', name: 'Gulfstream Park Racing & Casino', lat: 25.9760, lng: -80.1388, type: 'stadium', tags: 'estadio cancha carrera caballos hipodromo casino apuestas hallandale' },
  { id: 'ST_ARSHT', name: 'Adrienne Arsht Center', lat: 25.7885, lng: -80.1895, type: 'business', tags: 'teatro opera ballet sinfonica concierto show' },
  { id: 'ST_NEW_WORLD', name: 'New World Center (Miami Beach)', lat: 25.7915, lng: -80.1311, type: 'business', tags: 'teatro sinfonica concierto show musica' },
  { id: 'ST_FILLMORE', name: 'The Fillmore Miami Beach', lat: 25.7932, lng: -80.1325, type: 'business', tags: 'teatro concierto show musica jackie gleason' },
  { id: 'ST_OLYMPIA', name: 'Olympia Theater (Downtown)', lat: 25.7743, lng: -80.1901, type: 'business', tags: 'teatro concierto show musica' },
  { id: 'ST_KRAVIS', name: 'Kravis Center (WPB)', lat: 26.7067, lng: -80.0597, type: 'business', tags: 'teatro opera ballet sinfonica concierto show wpb' },
  { id: 'ST_BROWARD', name: 'Broward Center for the Performing Arts', lat: 26.1197, lng: -80.1479, type: 'business', tags: 'teatro opera ballet sinfonica concierto show ft lauderdale' },
  { id: 'ST_CONVENTION_MB', name: 'Miami Beach Convention Center', lat: 25.7946, lng: -80.1345, type: 'business', tags: 'centro convenciones evento feria art basel' },

  // ─── 🏙️ RESIDENCIAS VIP Y CONDOS DE LUJO ───
  { id: 'RES_BENTLEY', name: 'Bentley Residences (Sunny Isles)', lat: 25.9385, lng: -80.1200, type: 'residence', tags: 'edificio torre residence condo departamento luxury bently' },
  { id: 'RES_WALDORF', name: 'Waldorf Astoria Residences (Downtown)', lat: 25.7772, lng: -80.1891, type: 'residence', tags: 'edificio torre residence condo departamento luxury waldor astoria' },
  { id: 'RES_BACCARAT', name: 'Baccarat Residences (Brickell)', lat: 25.7681, lng: -80.1888, type: 'residence', tags: 'edificio torre residence condo departamento luxury bacarat cristal' },
  { id: 'RES_CIPRIANI', name: 'Cipriani Residences (Brickell)', lat: 25.7611, lng: -80.1915, type: 'residence', tags: 'edificio torre residence condo departamento luxury cipriani' },
  { id: 'RES_FENDI', name: 'Fendi Château Residences (Surfside)', lat: 25.8825, lng: -80.1215, type: 'residence', tags: 'edificio torre residence condo departamento luxury chateau boutique' },
  { id: 'RES_ARTE', name: 'Arte Surfside', lat: 25.8795, lng: -80.1211, type: 'residence', tags: 'edificio torre residence condo departamento luxury ivanka' },
  { id: 'RES_PORSCHE', name: 'Porsche Design Tower (Sunny Isles)', lat: 25.9288, lng: -80.1215, type: 'residence', tags: 'edificio torre residence condo departamento porshe porche luxury autos' },
  { id: 'RES_ARMANI', name: 'Residences by Armani/Casa (Sunny Isles)', lat: 25.9312, lng: -80.1211, type: 'residence', tags: 'edificio torre residence condo departamento luxury casa' },
  { id: 'RES_ASTON', name: 'Aston Martin Residences (Downtown)', lat: 25.7705, lng: -80.1856, type: 'residence', tags: 'edificio torre residence condo departamento astonmartin luxury' },
  { id: 'RES_MUSE', name: 'Muse Residences (Sunny Isles)', lat: 25.9250, lng: -80.1220, type: 'residence', tags: 'edificio torre residence condo departamento luxury' },
  { id: 'RES_JADE_SIG', name: 'Jade Signature (Sunny Isles)', lat: 25.9265, lng: -80.1218, type: 'residence', tags: 'edificio torre residence condo departamento yade luxury' },
  { id: 'RES_JADE_OCEAN', name: 'Jade Ocean (Sunny Isles)', lat: 25.9230, lng: -80.1220, type: 'residence', tags: 'edificio torre residence condo departamento yade luxury' },
  { id: 'RES_JADE_BEACH', name: 'Jade Beach (Sunny Isles)', lat: 25.9240, lng: -80.1220, type: 'residence', tags: 'edificio torre residence condo departamento yade luxury' },
  { id: 'RES_ESTATES_ACQ', name: 'The Estates at Acqualina (Sunny Isles)', lat: 25.9370, lng: -80.1204, type: 'residence', tags: 'edificio torre residence condo departamento aqualina akualina luxury' },
  { id: 'RES_REGALIA', name: 'Regalia Miami (Sunny Isles)', lat: 25.9555, lng: -80.1195, type: 'residence', tags: 'edificio torre residence condo departamento luxury' },
  { id: 'RES_TURNBERRY_OC', name: 'Turnberry Ocean Club Residences', lat: 25.9405, lng: -80.1200, type: 'residence', tags: 'edificio torre residence condo departamento luxury' },
  { id: 'RES_OCEANA_BAL', name: 'Oceana Bal Harbour', lat: 25.8970, lng: -80.1235, type: 'residence', tags: 'edificio torre residence condo departamento luxury oceaana' },
  { id: 'RES_OCEANA_KB', name: 'Oceana Key Biscayne', lat: 25.7001, lng: -80.1588, type: 'residence', tags: 'edificio torre residence condo departamento luxury oceaana' },
  { id: 'RES_EIGHTY_SEVEN', name: 'Eighty Seven Park (Miami Beach)', lat: 25.8675, lng: -80.1210, type: 'residence', tags: 'edificio torre residence condo departamento 87 park ochenta y siete' },
  { id: 'RES_CONTINUUM', name: 'Continuum South Beach', lat: 25.7675, lng: -80.1332, type: 'residence', tags: 'edificio torre residence condo departamento continum luxury' },
  { id: 'RES_APOGEE', name: 'Apogee South Beach', lat: 25.7681, lng: -80.1345, type: 'residence', tags: 'edificio torre residence condo departamento apoje apoji luxury' },
  { id: 'RES_MURANO', name: 'Murano at Portofino', lat: 25.7702, lng: -80.1365, type: 'residence', tags: 'edificio torre residence condo departamento luxury' },
  { id: 'RES_ICON', name: 'Icon Brickell', lat: 25.7688, lng: -80.1895, type: 'residence', tags: 'edificio torre residence condo departamento aicon luxury' },
  { id: 'RES_FLATIRON', name: 'Brickell Flatiron', lat: 25.7635, lng: -80.1932, type: 'residence', tags: 'edificio torre residence condo departamento luxury' },
  { id: 'RES_ECHO', name: 'Echo Brickell', lat: 25.7570, lng: -80.1925, type: 'residence', tags: 'edificio torre residence condo departamento eco luxury' },
  { id: 'RES_PANORAMA', name: 'Panorama Tower (Brickell)', lat: 25.7618, lng: -80.1905, type: 'residence', tags: 'edificio torre residence condo departamento luxury' },
  { id: 'RES_1000_MUSEUM', name: 'One Thousand Museum (Downtown)', lat: 25.7836, lng: -80.1901, type: 'residence', tags: 'edificio torre residence condo departamento 1000 zaha hadid luxury mil' },
  { id: 'RES_PARAMOUNT', name: 'Paramount Miami Worldcenter', lat: 25.7815, lng: -80.1915, type: 'residence', tags: 'edificio torre residence condo departamento luxury world center' },
  { id: 'RES_ELYSEE', name: 'Elysee Miami (Edgewater)', lat: 25.8010, lng: -80.1865, type: 'residence', tags: 'edificio torre residence condo departamento elise luxury' },
  { id: 'RES_MISSONI', name: 'Missoni Baia (Edgewater)', lat: 25.8025, lng: -80.1860, type: 'residence', tags: 'edificio torre residence condo departamento misoni luxury' },
  { id: 'RES_ARIA', name: 'Aria Reserve (Edgewater)', lat: 25.8050, lng: -80.1855, type: 'residence', tags: 'edificio torre residence condo departamento luxury' },
  { id: 'RES_BRISTOL', name: 'The Bristol Palm Beach', lat: 26.7085, lng: -80.0465, type: 'residence', tags: 'edificio torre residence condo departamento luxury wpb bristl' },
  { id: 'RES_UNA', name: 'Una Residences (Brickell)', lat: 25.7511, lng: -80.1966, type: 'residence', tags: 'edificio torre residence condo departamento luxury' },
  { id: 'RES_REACH_RISE', name: 'Reach & Rise at Brickell City Centre', lat: 25.7665, lng: -80.1935, type: 'residence', tags: 'edificio torre residence condo departamento luxury' },
  { id: 'RES_MARQUIS', name: 'Marquis Residences (Downtown)', lat: 25.7850, lng: -80.1880, type: 'residence', tags: 'edificio torre residence condo departamento luxury marquies' },
  { id: 'RES_TEN_MUSEUM', name: 'Ten Museum Park', lat: 25.7845, lng: -80.1885, type: 'residence', tags: 'edificio torre residence condo departamento luxury 10' },
  { id: 'RES_RITZ_MB', name: 'The Ritz-Carlton Residences (Miami Beach)', lat: 25.8235, lng: -80.1332, type: 'residence', tags: 'edificio torre residence condo departamento luxury rits' },
  { id: 'RES_RITZ_SUNNY', name: 'The Ritz-Carlton Residences (Sunny Isles)', lat: 25.9348, lng: -80.1210, type: 'residence', tags: 'edificio torre residence condo departamento luxury rits' },
  { id: 'RES_STREGIS_BRICKELL', name: 'The St. Regis Residences (Brickell)', lat: 25.7575, lng: -80.1920, type: 'residence', tags: 'edificio torre residence condo departamento luxury san regis' },
  { id: 'RES_PERIGON', name: 'The Perigon (Miami Beach)', lat: 25.8450, lng: -80.1205, type: 'residence', tags: 'edificio torre residence condo departamento luxury mid beach' },
  { id: 'RES_FIVE_PARK', name: 'Five Park Miami Beach', lat: 25.7720, lng: -80.1385, type: 'residence', tags: 'edificio torre residence condo departamento luxury' },

  // ─── 🏨 HOTELES: MIAMI BEACH, SOUTH BEACH & SURFSIDE ───
  { id: 'HTL_FONTAINEBLEAU', name: 'Fontainebleau Miami Beach', lat: 25.8180, lng: -80.1224, type: 'hotel', tags: 'hotel hospedaje resort alojamiento cuarto habitacion fontenbleu fontenebro' },
  { id: 'HTL_FAENA', name: 'Faena Hotel Miami Beach', lat: 25.8075, lng: -80.1235, type: 'hotel', tags: 'hotel hospedaje resort alojamiento cuarto habitacion lujo' },
  { id: 'HTL_1HOTEL', name: '1 Hotel South Beach', lat: 25.7997, lng: -80.1275, type: 'hotel', tags: 'hotel hospedaje resort alojamiento cuarto habitacion one' },
  { id: 'HTL_SETAI', name: 'The Setai Miami Beach', lat: 25.7957, lng: -80.1287, type: 'hotel', tags: 'hotel hospedaje resort alojamiento cuarto habitacion' },
  { id: 'HTL_W_SOBE', name: 'W South Beach', lat: 25.7979, lng: -80.1281, type: 'hotel', tags: 'hotel hospedaje resort alojamiento cuarto habitacion doble u' },
  { id: 'HTL_RITZ_SOBE', name: 'The Ritz-Carlton, South Beach', lat: 25.7909, lng: -80.1286, type: 'hotel', tags: 'hotel hospedaje resort alojamiento cuarto habitacion rits ritzcarlton' },
  { id: 'HTL_EDITION', name: 'The Miami Beach EDITION', lat: 25.8045, lng: -80.1245, type: 'hotel', tags: 'hotel hospedaje resort alojamiento cuarto habitacion edicion' },
  { id: 'HTL_MONDRIAN', name: 'Mondrian South Beach', lat: 25.7806, lng: -80.1419, type: 'hotel', tags: 'hotel hospedaje resort alojamiento cuarto habitacion' },
  { id: 'HTL_STANDARD', name: 'The Standard Spa, Miami Beach', lat: 25.7895, lng: -80.1478, type: 'hotel', tags: 'hotel hospedaje resort alojamiento cuarto habitacion spa' },
  { id: 'HTL_SOHO', name: 'Soho Beach House Miami', lat: 25.8155, lng: -80.1222, type: 'hotel', tags: 'hotel hospedaje resort alojamiento cuarto habitacion club privado sojo' },
  { id: 'HTL_VILLA_CASA', name: 'The Villa Casa Casuarina (Versace)', lat: 25.7820, lng: -80.1303, type: 'hotel', tags: 'hotel hospedaje resort alojamiento cuarto habitacion mansion versace' },
  { id: 'HTL_EDEN_ROC', name: 'Eden Roc Miami Beach', lat: 25.8206, lng: -80.1215, type: 'hotel', tags: 'hotel hospedaje resort alojamiento cuarto habitacion edenroc' },
  { id: 'HTL_GOODTIME', name: 'The Goodtime Hotel', lat: 25.7744, lng: -80.1332, type: 'hotel', tags: 'hotel hospedaje resort alojamiento cuarto habitacion gudtime' },
  { id: 'HTL_SLS_SOBE', name: 'SLS South Beach', lat: 25.7938, lng: -80.1292, type: 'hotel', tags: 'hotel hospedaje resort alojamiento cuarto habitacion' },
  { id: 'HTL_BETSY', name: 'The Betsy Hotel South Beach', lat: 25.7865, lng: -80.1305, type: 'hotel', tags: 'hotel hospedaje resort alojamiento cuarto habitacion betsi' },
  { id: 'HTL_NATIONAL', name: 'National Hotel Miami Beach', lat: 25.7925, lng: -80.1295, type: 'hotel', tags: 'hotel hospedaje resort alojamiento cuarto habitacion' },
  { id: 'HTL_NOBU', name: 'Nobu Hotel Miami Beach', lat: 25.8210, lng: -80.1215, type: 'hotel', tags: 'hotel hospedaje resort alojamiento cuarto habitacion eden roc' },
  { id: 'HTL_CARILLON', name: 'Carillon Miami Wellness Resort', lat: 25.8525, lng: -80.1195, type: 'hotel', tags: 'hotel hospedaje resort alojamiento cuarto habitacion spa carilon' },
  { id: 'HTL_BVLGARI', name: 'Bvlgari Hotel Miami Beach', lat: 25.7960, lng: -80.1280, type: 'hotel', tags: 'hotel hospedaje resort alojamiento cuarto habitacion bulgari' },
  { id: 'HTL_AMAN', name: 'Aman Miami Beach', lat: 25.8080, lng: -80.1230, type: 'hotel', tags: 'hotel hospedaje resort alojamiento cuarto habitacion lujo' },
  { id: 'HTL_PLYMOUTH', name: 'The Plymouth South Beach', lat: 25.7960, lng: -80.1290, type: 'hotel', tags: 'hotel hospedaje resort alojamiento cuarto habitacion plimouth' },
  { id: 'HTL_NAUTILUS', name: 'Nautilus by Arlo', lat: 25.7938, lng: -80.1282, type: 'hotel', tags: 'hotel hospedaje resort alojamiento cuarto habitacion' },
  { id: 'HTL_DELANO', name: 'Delano South Beach', lat: 25.7928, lng: -80.1292, type: 'hotel', tags: 'hotel hospedaje resort alojamiento cuarto habitacion' },
  { id: 'HTL_GALE', name: 'Gale South Beach', lat: 25.7920, lng: -80.1305, type: 'hotel', tags: 'hotel hospedaje resort alojamiento cuarto habitacion' },
  { id: 'HTL_MOXY_SOBE', name: 'Moxy Miami South Beach', lat: 25.7825, lng: -80.1325, type: 'hotel', tags: 'hotel hospedaje resort alojamiento cuarto habitacion moxi' },
  { id: 'HTL_CONFIDANTE', name: 'The Confidante (Andaz Miami Beach)', lat: 25.8115, lng: -80.1228, type: 'hotel', tags: 'hotel hospedaje resort alojamiento cuarto habitacion andas' },
  { id: 'HTL_SAVOY', name: 'The Savoy Hotel & Beach Club', lat: 25.7725, lng: -80.1320, type: 'hotel', tags: 'hotel hospedaje resort alojamiento cuarto habitacion' },

  // ─── 🏨 HOTELES: BRICKELL, DOWNTOWN & COCONUT GROVE ───
  { id: 'HTL_MANDARIN', name: 'Mandarin Oriental, Miami (Brickell Key)', lat: 25.7661, lng: -80.1848, type: 'hotel', tags: 'hotel hospedaje resort alojamiento cuarto habitacion lujo' },
  { id: 'HTL_FOUR_BRICKELL', name: 'Four Seasons Hotel Miami', lat: 25.7591, lng: -80.1918, type: 'hotel', tags: 'hotel hospedaje resort alojamiento cuarto habitacion 4 seasons' },
  { id: 'HTL_EAST', name: 'EAST Miami (Brickell City Centre)', lat: 25.7665, lng: -80.1926, type: 'hotel', tags: 'hotel hospedaje resort alojamiento cuarto habitacion este' },
  { id: 'HTL_SLS_BRICKELL', name: 'SLS Brickell', lat: 25.7615, lng: -80.1920, type: 'hotel', tags: 'hotel hospedaje resort alojamiento cuarto habitacion' },
  { id: 'HTL_INTERCONT', name: 'InterContinental Miami', lat: 25.7725, lng: -80.1843, type: 'hotel', tags: 'hotel hospedaje resort alojamiento cuarto habitacion inter continental' },
  { id: 'HTL_JWMARRIOTT', name: 'JW Marriott Marquis Miami', lat: 25.7712, lng: -80.1898, type: 'hotel', tags: 'hotel hospedaje resort alojamiento cuarto habitacion mariot jw' },
  { id: 'HTL_KIMPTON_EPIC', name: 'Kimpton EPIC Hotel', lat: 25.7709, lng: -80.1896, type: 'hotel', tags: 'hotel hospedaje resort alojamiento cuarto habitacion epico' },
  { id: 'HTL_GABRIEL', name: 'The Gabriel Miami Downtown', lat: 25.7850, lng: -80.1885, type: 'hotel', tags: 'hotel hospedaje resort alojamiento cuarto habitacion curio' },
  { id: 'HTL_BILTMORE', name: 'The Biltmore Hotel Coral Gables', lat: 25.7410, lng: -80.2783, type: 'hotel', tags: 'hotel hospedaje resort alojamiento cuarto habitacion bilmor' },
  { id: 'HTL_RITZ_COCO', name: 'The Ritz-Carlton, Coconut Grove', lat: 25.7289, lng: -80.2407, type: 'hotel', tags: 'hotel hospedaje resort alojamiento cuarto habitacion rits' },
  { id: 'HTL_MAYFAIR', name: 'Mayfair House Hotel & Garden', lat: 25.7297, lng: -80.2425, type: 'hotel', tags: 'hotel hospedaje resort alojamiento cuarto habitacion' },
  { id: 'HTL_MR_C', name: 'Mr. C Miami - Coconut Grove', lat: 25.7285, lng: -80.2420, type: 'hotel', tags: 'hotel hospedaje resort alojamiento cuarto habitacion mister c cipriani' },
  { id: 'HTL_MUTINY', name: 'The Mutiny Hotel (Coconut Grove)', lat: 25.7281, lng: -80.2405, type: 'hotel', tags: 'hotel hospedaje resort alojamiento cuarto habitacion mutini' },
  { id: 'HTL_CITIZENM_BRICKELL', name: 'citizenM Miami Brickell', lat: 25.7645, lng: -80.1930, type: 'hotel', tags: 'hotel hospedaje resort alojamiento cuarto habitacion citizem' },
  { id: 'HTL_CITIZENM_DWNTWN', name: 'citizenM Miami Worldcenter', lat: 25.7815, lng: -80.1895, type: 'hotel', tags: 'hotel hospedaje resort alojamiento cuarto habitacion citizem' },
  { id: 'HTL_YOTEL_DWNTWN', name: 'YOTEL Miami', lat: 25.7758, lng: -80.1890, type: 'hotel', tags: 'hotel hospedaje resort alojamiento cuarto habitacion iotel' },
  { id: 'HTL_W_MIAMI', name: 'W Miami (Brickell)', lat: 25.7688, lng: -80.1895, type: 'hotel', tags: 'hotel hospedaje resort alojamiento cuarto habitacion doble u' },

  // ─── 🏨 HOTELES: BAL HARBOUR, SUNNY ISLES, FTL & PALM BEACH ───
  { id: 'HTL_STREGIS_BAL', name: 'The St. Regis Bal Harbour Resort', lat: 25.8895, lng: -80.1226, type: 'hotel', tags: 'hotel hospedaje resort alojamiento cuarto habitacion san regis' },
  { id: 'HTL_RITZ_BAL', name: 'The Ritz-Carlton Bal Harbour', lat: 25.9015, lng: -80.1234, type: 'hotel', tags: 'hotel hospedaje resort alojamiento cuarto habitacion rits' },
  { id: 'HTL_ACQUALINA', name: 'Acqualina Resort Sunny Isles', lat: 25.9363, lng: -80.1206, type: 'hotel', tags: 'hotel hospedaje resort alojamiento cuarto habitacion aqualina akualina' },
  { id: 'HTL_FOUR_SURF', name: 'Four Seasons Hotel at The Surf Club', lat: 25.8752, lng: -80.1213, type: 'hotel', tags: 'hotel hospedaje resort alojamiento cuarto habitacion 4 seasons surfside' },
  { id: 'HTL_JW_TURNBERRY', name: 'JW Marriott Miami Turnberry (Aventura)', lat: 25.9602, lng: -80.1309, type: 'hotel', tags: 'hotel hospedaje resort alojamiento cuarto habitacion mariot jw turnbery' },
  { id: 'HTL_HARDROCK_GUITAR', name: 'Seminole Hard Rock (Guitar Hotel)', lat: 26.0415, lng: -80.2105, type: 'hotel', tags: 'hotel hospedaje resort alojamiento cuarto habitacion guitarra casino hollywood' },
  { id: 'HTL_DIPLOMAT', name: 'The Diplomat Beach Resort Hollywood', lat: 25.9925, lng: -80.1170, type: 'hotel', tags: 'hotel hospedaje resort alojamiento cuarto habitacion' },
  { id: 'HTL_MARGARITAVILLE', name: 'Margaritaville Hollywood Beach', lat: 26.0145, lng: -80.1160, type: 'hotel', tags: 'hotel hospedaje resort alojamiento cuarto habitacion' },
  { id: 'HTL_FOUR_FTL', name: 'Four Seasons Hotel Fort Lauderdale', lat: 26.1265, lng: -80.1030, type: 'hotel', tags: 'hotel hospedaje resort alojamiento cuarto habitacion 4 seasons for lodordel' },
  { id: 'HTL_RITZ_FTL', name: 'The Ritz-Carlton Fort Lauderdale', lat: 26.1240, lng: -80.1040, type: 'hotel', tags: 'hotel hospedaje resort alojamiento cuarto habitacion rits' },
  { id: 'HTL_W_FTL', name: 'W Fort Lauderdale', lat: 26.1285, lng: -80.1035, type: 'hotel', tags: 'hotel hospedaje resort alojamiento cuarto habitacion doble u' },
  { id: 'HTL_CONRAD_FTL', name: 'Conrad Fort Lauderdale Beach', lat: 26.1330, lng: -80.1025, type: 'hotel', tags: 'hotel hospedaje resort alojamiento cuarto habitacion' },
  { id: 'HTL_DALMAR_FTL', name: 'The Dalmar Fort Lauderdale', lat: 26.1248, lng: -80.1412, type: 'hotel', tags: 'hotel hospedaje resort alojamiento cuarto habitacion downtown tribute' },
  { id: 'HTL_PELICAN_GRAND', name: 'Pelican Grand Beach Resort (FTL)', lat: 26.1480, lng: -80.1020, type: 'hotel', tags: 'hotel hospedaje resort alojamiento cuarto habitacion' },
  { id: 'HTL_WESTIN_FTL', name: 'The Westin Fort Lauderdale Beach', lat: 26.1245, lng: -80.1045, type: 'hotel', tags: 'hotel hospedaje resort alojamiento cuarto habitacion' },
  { id: 'HTL_RAY_DELRAY', name: 'The Ray Hotel Delray Beach', lat: 26.4630, lng: -80.0700, type: 'hotel', tags: 'hotel hospedaje resort alojamiento cuarto habitacion' },
  { id: 'HTL_BREAKERS', name: 'The Breakers Palm Beach', lat: 26.7145, lng: -80.0335, type: 'hotel', tags: 'hotel hospedaje resort alojamiento cuarto habitacion lujo wpb' },
  { id: 'HTL_BEN_WPB', name: 'The Ben, Autograph Collection (WPB)', lat: 26.7150, lng: -80.0500, type: 'hotel', tags: 'hotel hospedaje resort alojamiento cuarto habitacion wpb' },
  { id: 'HTL_EAU_PALM', name: 'Eau Palm Beach Resort & Spa', lat: 26.5775, lng: -80.0385, type: 'hotel', tags: 'hotel hospedaje resort alojamiento cuarto habitacion' },
  { id: 'HTL_BOCA_RATON', name: 'The Boca Raton (Resort)', lat: 26.3425, lng: -80.0765, type: 'hotel', tags: 'hotel hospedaje resort alojamiento cuarto habitacion voca' },
  { id: 'HTL_FOUR_PB', name: 'Four Seasons Resort Palm Beach', lat: 26.6110, lng: -80.0380, type: 'hotel', tags: 'hotel hospedaje resort alojamiento cuarto habitacion 4 seasons' },
  { id: 'HTL_COLONY_PB', name: 'The Colony Hotel Palm Beach', lat: 26.7020, lng: -80.0375, type: 'hotel', tags: 'hotel hospedaje resort alojamiento cuarto habitacion coloni' },

  // ─── 🏨 HOTELES: RESORTS EN LOS CAYOS Y ORLANDO ───
  { id: 'HTL_FISHER_ISLAND', name: 'Fisher Island Club Resort', lat: 25.7615, lng: -80.1420, type: 'hotel', tags: 'hotel hospedaje resort alojamiento cuarto habitacion isla privada fisher' },
  { id: 'HTL_LITTLE_PALM', name: 'Little Palm Island Resort & Spa', lat: 24.6225, lng: -81.3965, type: 'hotel', tags: 'hotel hospedaje resort alojamiento cuarto habitacion cayos keys' },
  { id: 'HTL_CHEECA', name: 'Cheeca Lodge & Spa (Islamorada)', lat: 24.9250, lng: -80.6250, type: 'hotel', tags: 'hotel hospedaje resort alojamiento cuarto habitacion cayos keys chica' },
  { id: 'HTL_HAWKS_CAY', name: 'Hawks Cay Resort (Duck Key)', lat: 24.7645, lng: -80.9415, type: 'hotel', tags: 'hotel hospedaje resort alojamiento cuarto habitacion cayos keys' },
  { id: 'HTL_CASA_MARINA', name: 'Casa Marina Key West, Curio Collection', lat: 24.5450, lng: -81.7915, type: 'hotel', tags: 'hotel hospedaje resort alojamiento cuarto habitacion cayos keys waldorf' },
  { id: 'HTL_OCEAN_KEY', name: 'Ocean Key Resort & Spa (Key West)', lat: 24.5590, lng: -81.8080, type: 'hotel', tags: 'hotel hospedaje resort alojamiento cuarto habitacion cayos keys' },
  { id: 'HTL_WALDORF_ORL', name: 'Waldorf Astoria Orlando', lat: 28.3370, lng: -81.5235, type: 'hotel', tags: 'hotel hospedaje resort alojamiento cuarto habitacion waldor astoria' },
  { id: 'HTL_RITZ_ORL', name: 'The Ritz-Carlton Orlando, Grande Lakes', lat: 28.4045, lng: -81.4320, type: 'hotel', tags: 'hotel hospedaje resort alojamiento cuarto habitacion rits' },
  { id: 'HTL_FOUR_ORL', name: 'Four Seasons Resort Orlando (Disney)', lat: 28.3970, lng: -81.5435, type: 'hotel', tags: 'hotel hospedaje resort alojamiento cuarto habitacion 4 seasons' },

  // ─── 🛍️ SHOPPINGS, RETAIL DE LUJO Y AVENIDAS ───
  { id: 'SHOP_BALHARBOUR', name: 'Bal Harbour Shops', lat: 25.8885, lng: -80.1260, type: 'shopping', tags: 'compras mall outlet comprar ropa tiendas shopping centro comercial' },
  { id: 'SHOP_DESIGN', name: 'Miami Design District', lat: 25.8130, lng: -80.1933, type: 'shopping', tags: 'compras mall outlet comprar ropa tiendas shopping centro comercial lujo dior louis vuitton' },
  { id: 'SHOP_BRICKELL', name: 'Brickell City Centre', lat: 25.7675, lng: -80.1930, type: 'shopping', tags: 'compras mall outlet comprar ropa tiendas shopping centro comercial citi center' },
  { id: 'SHOP_AVENTURA', name: 'Aventura Mall', lat: 25.9566, lng: -80.1432, type: 'shopping', tags: 'compras mall outlet comprar ropa tiendas shopping centro comercial' },
  { id: 'SHOP_SAWGRASS', name: 'Sawgrass Mills (Sunrise)', lat: 26.1531, lng: -80.3223, type: 'shopping', tags: 'compras mall outlet comprar ropa tiendas shopping centro comercial sagras sougras' },
  { id: 'SHOP_DOLPHIN', name: 'Dolphin Mall', lat: 25.7885, lng: -80.3802, type: 'shopping', tags: 'compras mall outlet comprar ropa tiendas shopping centro comercial dolfin' },
  { id: 'SHOP_LINCOLN', name: 'Lincoln Road Mall (South Beach)', lat: 25.7906, lng: -80.1362, type: 'shopping', tags: 'compras mall outlet comprar ropa tiendas shopping centro comercial calle peatonal' },
  { id: 'SHOP_MERRICK', name: 'Shops at Merrick Park (Coral Gables)', lat: 25.7344, lng: -80.2587, type: 'shopping', tags: 'compras mall outlet comprar ropa tiendas shopping centro comercial merik' },
  { id: 'SHOP_BAYSIDE', name: 'Bayside Marketplace', lat: 25.7780, lng: -80.1868, type: 'shopping', tags: 'compras mall outlet comprar ropa tiendas shopping centro comercial puerto' },
  { id: 'SHOP_WORTH_AVE', name: 'Worth Avenue (Palm Beach)', lat: 26.6990, lng: -80.0385, type: 'shopping', tags: 'compras mall outlet comprar ropa tiendas shopping avenida worf av lujo' },
  { id: 'SHOP_LAS_OLAS', name: 'Las Olas Boulevard (Fort Lauderdale)', lat: 26.1190, lng: -80.1350, type: 'shopping', tags: 'compras mall outlet comprar ropa tiendas shopping avenida restaurante' },
  { id: 'SHOP_TOWN_CENTER', name: 'Town Center at Boca Raton', lat: 26.3600, lng: -80.1250, type: 'shopping', tags: 'compras mall outlet comprar ropa tiendas shopping centro comercial voca' },
  { id: 'SHOP_GALLERIA', name: 'The Galleria at Fort Lauderdale', lat: 26.1365, lng: -80.1130, type: 'shopping', tags: 'compras mall outlet comprar ropa tiendas shopping centro comercial galeria' },
  { id: 'SHOP_DADELAND', name: 'Dadeland Mall (Kendall)', lat: 25.6940, lng: -80.3135, type: 'shopping', tags: 'compras mall outlet comprar ropa tiendas shopping centro comercial deidland' },
  { id: 'SHOP_THE_FALLS', name: 'The Falls (Pinecrest)', lat: 25.6425, lng: -80.3340, type: 'shopping', tags: 'compras mall outlet comprar ropa tiendas shopping centro comercial falls' },
  { id: 'SHOP_SUNSET_PLACE', name: 'Shops at Sunset Place (South Miami)', lat: 25.7040, lng: -80.2935, type: 'shopping', tags: 'compras mall outlet comprar ropa tiendas shopping centro comercial' },
  { id: 'SHOP_RIVER_LANDING', name: 'River Landing Shops', lat: 25.7955, lng: -80.2140, type: 'shopping', tags: 'compras mall outlet comprar ropa tiendas shopping centro comercial' },
  { id: 'SHOP_COCOWALK', name: 'CocoWalk (Coconut Grove)', lat: 25.7290, lng: -80.2440, type: 'shopping', tags: 'compras mall outlet comprar ropa tiendas shopping centro comercial' },

  // ─── 🏥 HOSPITALES Y CENTROS MÉDICOS DE REFERENCIA ───
  { id: 'MED_JACKSON', name: 'Jackson Memorial Hospital', lat: 25.7905, lng: -80.2045, type: 'business', tags: 'hospital clinica medico salud emergencia medical center doctor' },
  { id: 'MED_BAPTIST_KENDALL', name: 'Baptist Hospital of Miami (Kendall)', lat: 25.6881, lng: -80.3541, type: 'business', tags: 'hospital clinica medico salud emergencia medical center doctor bautista' },
  { id: 'MED_MOUNT_SINAI', name: 'Mount Sinai Medical Center (Miami Beach)', lat: 25.8143, lng: -80.1374, type: 'business', tags: 'hospital clinica medico salud emergencia medical center doctor monte sinai' },
  { id: 'MED_CLEVELAND', name: 'Cleveland Clinic Florida (Weston)', lat: 26.0963, lng: -80.3592, type: 'business', tags: 'hospital clinica medico salud emergencia medical center doctor cleveland' },
  { id: 'MED_BASCOM', name: 'Bascom Palmer Eye Institute', lat: 25.7901, lng: -80.2030, type: 'business', tags: 'hospital clinica medico salud ojos vision vista' },
  { id: 'MED_SYLVESTER', name: 'Sylvester Comprehensive Cancer Center', lat: 25.7915, lng: -80.2040, type: 'business', tags: 'hospital clinica medico salud cancer oncologia silvester' },
  { id: 'MED_NICKLAUS', name: 'Nicklaus Children\'s Hospital', lat: 25.7380, lng: -80.2985, type: 'business', tags: 'hospital clinica medico salud ninos pediatria infantil niklaus' },
  { id: 'MED_HOLY_CROSS', name: 'Holy Cross Hospital (FTL)', lat: 26.1850, lng: -80.1180, type: 'business', tags: 'hospital clinica medico salud emergencia joly' },
  { id: 'MED_SOUTH_MIAMI', name: 'South Miami Hospital', lat: 25.7025, lng: -80.2855, type: 'business', tags: 'hospital clinica medico salud emergencia medical center doctor' },
  { id: 'MED_MERCY', name: 'Mercy Hospital (Coconut Grove)', lat: 25.7410, lng: -80.2185, type: 'business', tags: 'hospital clinica medico salud emergencia medical center doctor mersi' },
  { id: 'MED_JACKSON_SOUTH', name: 'Jackson South Medical Center', lat: 25.6175, lng: -80.3475, type: 'business', tags: 'hospital clinica medico salud emergencia medical center doctor' },
  { id: 'MED_MEMORIAL_REGIONAL', name: 'Memorial Regional Hospital (Hollywood)', lat: 26.0210, lng: -80.1775, type: 'business', tags: 'hospital clinica medico salud emergencia medical center doctor' },
  { id: 'MED_BOCA_REGIONAL', name: 'Boca Raton Regional Hospital', lat: 26.3685, lng: -80.1005, type: 'business', tags: 'hospital clinica medico salud emergencia medical center doctor voca' },

  // ─── 🎓 UNIVERSIDADES ───
  { id: 'EDU_UM', name: 'University of Miami (Coral Gables)', lat: 25.7204, lng: -80.2764, type: 'business', tags: 'universidad facultad campus college edu estudiante u of m' },
  { id: 'EDU_FIU_MODESTO', name: 'FIU - Modesto A. Maidique Campus', lat: 25.7562, lng: -80.3755, type: 'business', tags: 'universidad facultad campus college edu florida international' },
  { id: 'EDU_MDC', name: 'Miami Dade College (Wolfson Campus)', lat: 25.7785, lng: -80.1895, type: 'business', tags: 'universidad facultad campus college edu dade' },
  { id: 'EDU_NSU', name: 'Nova Southeastern University (NSU)', lat: 26.0795, lng: -80.2455, type: 'business', tags: 'universidad facultad campus college edu nova' },
  { id: 'EDU_BARRY', name: 'Barry University', lat: 25.8790, lng: -80.1945, type: 'business', tags: 'universidad facultad campus college edu bari' },
  { id: 'EDU_FAU', name: 'Florida Atlantic University (FAU Boca Raton)', lat: 26.3725, lng: -80.1010, type: 'business', tags: 'universidad facultad campus college edu voca atlantic' },

  // ─── ⛳ CAMPOS DE GOLF Y COUNTRY CLUBS VIP ───
  { id: 'GOLF_TRUMP_DORAL', name: 'Trump National Doral Miami', lat: 25.8141, lng: -80.3458, type: 'park', tags: 'golf parque park verde hoyo club country resort' },
  { id: 'GOLF_TURNBERRY', name: 'Turnberry Isle Country Club (Aventura)', lat: 25.9585, lng: -80.1340, type: 'park', tags: 'golf parque park verde hoyo club country resort' },
  { id: 'GOLF_INDIAN_CREEK', name: 'Indian Creek Country Club', lat: 25.8791, lng: -80.1293, type: 'park', tags: 'golf parque park verde hoyo club country resort' },
  { id: 'GOLF_LA_GORCE', name: 'La Gorce Country Club (Miami Beach)', lat: 25.8450, lng: -80.1306, type: 'park', tags: 'golf parque park verde hoyo club country resort' },
  { id: 'GOLF_BEARS_CLUB', name: 'The Bear\'s Club (Jupiter)', lat: 26.8970, lng: -80.0820, type: 'park', tags: 'golf parque park verde hoyo club country resort osos vip' },
  { id: 'GOLF_PGA', name: 'PGA National Resort (Palm Beach Gardens)', lat: 26.8285, lng: -80.1360, type: 'park', tags: 'golf parque park verde hoyo club country resort profesional' },
  { id: 'GOLF_SEMINOLE', name: 'Seminole Golf Club (Juno Beach)', lat: 26.8520, lng: -80.0450, type: 'park', tags: 'golf parque park verde hoyo club country resort exclusivo' },
  { id: 'GOLF_MIAMI_BEACH', name: 'Miami Beach Golf Club', lat: 25.8010, lng: -80.1390, type: 'park', tags: 'golf parque park verde hoyo club country resort' },
  { id: 'GOLF_CRANDON', name: 'Crandon Golf at Key Biscayne', lat: 25.7130, lng: -80.1550, type: 'park', tags: 'golf parque park verde hoyo club country resort cayo viscayn' },
  { id: 'GOLF_DEERING_BAY', name: 'Deering Bay Yacht & Country Club', lat: 25.6320, lng: -80.2920, type: 'park', tags: 'golf parque park verde hoyo club country resort yate diring' },
  { id: 'GOLF_BILTMORE', name: 'The Biltmore Golf Course (Coral Gables)', lat: 25.7415, lng: -80.2800, type: 'park', tags: 'golf parque park verde hoyo club country resort bilmor' },
  { id: 'GOLF_RIVIERA', name: 'Riviera Country Club (Coral Gables)', lat: 25.7160, lng: -80.2690, type: 'park', tags: 'golf parque park verde hoyo club country resort ribiera' },
  { id: 'GOLF_NORMANDY', name: 'Normandy Shores Golf Club', lat: 25.8560, lng: -80.1375, type: 'park', tags: 'golf parque park verde hoyo club country resort' },

  // ─── 🌳 ATRACCIONES, PARQUES Y MUSEOS ───
  { id: 'ATT_PEREZ', name: 'Pérez Art Museum Miami (PAMM)', lat: 25.7865, lng: -80.1856, type: 'business', tags: 'museo arte atraccion turismo perez art museum' },
  { id: 'ATT_FROST', name: 'Phillip and Patricia Frost Museum of Science', lat: 25.7850, lng: -80.1868, type: 'business', tags: 'museo ciencia atraccion turismo planetario acuario' },
  { id: 'ATT_ZOO', name: 'Zoo Miami', lat: 25.6067, lng: -80.4005, type: 'park', tags: 'parque atraccion turismo animales zoologico' },
  { id: 'ATT_VIZCAYA', name: 'Vizcaya Museum and Gardens', lat: 25.7444, lng: -80.2105, type: 'business', tags: 'museo arte atraccion turismo jardines vizcacha biscaya' },
  { id: 'ATT_WYNWOOD_WALLS', name: 'Wynwood Walls', lat: 25.8010, lng: -80.1993, type: 'park', tags: 'museo arte atraccion turismo paredes graffitis winwud' },
  { id: 'ATT_NORTON', name: 'Norton Museum of Art (WPB)', lat: 26.7020, lng: -80.0540, type: 'business', tags: 'museo arte atraccion turismo wpb' },
  { id: 'ATT_MORIKAMI', name: 'Morikami Museum and Japanese Gardens', lat: 26.4255, lng: -80.1470, type: 'park', tags: 'museo arte atraccion turismo jardines japoneses delray' },
  { id: 'ATT_FAIRCHILD', name: 'Fairchild Tropical Botanic Garden', lat: 25.6770, lng: -80.2745, type: 'park', tags: 'parque atraccion turismo botanico plantas jardin' },
  { id: 'ATT_DEERING', name: 'Deering Estate', lat: 25.6155, lng: -80.3115, type: 'park', tags: 'parque atraccion turismo mansion diring historico' },
  { id: 'ATT_SEAQUARIUM', name: 'Miami Seaquarium', lat: 25.7335, lng: -80.1645, type: 'park', tags: 'parque atraccion turismo acuario peces' },
  { id: 'ATT_JUNGLE', name: 'Jungle Island', lat: 25.7830, lng: -80.1740, type: 'park', tags: 'parque atraccion turismo isla animales' },
  { id: 'ATT_BAYFRONT', name: 'Bayfront Park', lat: 25.7745, lng: -80.1850, type: 'park', tags: 'parque atraccion turismo bahia downtown ultra evento' },

  // ─── 📍 ISLAS EXCLUSIVAS Y "BILLIONAIRE BUNKERS" ───
  { id: 'LOC_INDIAN_CREEK', name: 'Indian Creek Village', lat: 25.8785, lng: -80.1305, type: 'residence', tags: 'ciudad barrio zona area city town isla cayo bunker millonarios' },
  { id: 'LOC_STAR_ISLAND', name: 'Star Island', lat: 25.7770, lng: -80.1542, type: 'residence', tags: 'ciudad barrio zona area city town isla estrella mansion' },
  { id: 'LOC_HIBISCUS_ISLAND', name: 'Hibiscus Island', lat: 25.7820, lng: -80.1610, type: 'residence', tags: 'ciudad barrio zona area city town isla ibiscus' },
  { id: 'LOC_PALM_ISLAND', name: 'Palm Island', lat: 25.7795, lng: -80.1601, type: 'residence', tags: 'ciudad barrio zona area city town isla palmera' },
  { id: 'LOC_FISHER_ISLAND', name: 'Fisher Island', lat: 25.7601, lng: -80.1396, type: 'beach', tags: 'ciudad barrio zona area city town isla privada fisher' },
  { id: 'LOC_VENETIAN', name: 'Venetian Islands', lat: 25.7915, lng: -80.1610, type: 'residence', tags: 'ciudad barrio zona area city town islas venecianas san marco di lido rivo alto' },
  { id: 'LOC_SUNSET_ISLANDS', name: 'Sunset Islands', lat: 25.8060, lng: -80.1420, type: 'residence', tags: 'ciudad barrio zona area city town islas atardecer 1 2 3 4' },
  { id: 'LOC_LA_GORCE_ISLAND', name: 'La Gorce Island', lat: 25.8470, lng: -80.1310, type: 'residence', tags: 'ciudad barrio zona area city town isla gorse' },
  { id: 'LOC_ALLISON_ISLAND', name: 'Allison Island', lat: 25.8450, lng: -80.1230, type: 'residence', tags: 'ciudad barrio zona area city town isla alison' },
  { id: 'LOC_NORMANDY_ISLE', name: 'Normandy Isle', lat: 25.8520, lng: -80.1320, type: 'residence', tags: 'ciudad barrio zona area city town isla normandia' },
  { id: 'LOC_BAY_HARBOUR_ISLANDS', name: 'Bay Harbor Islands', lat: 25.8890, lng: -80.1330, type: 'residence', tags: 'ciudad barrio zona area city town islas bahia jarbor' },
  { id: 'LOC_GOLDEN_BEACH', name: 'Golden Beach', lat: 25.9660, lng: -80.1190, type: 'beach', tags: 'ciudad barrio zona area city town playa dorada mansion' },
  { id: 'LOC_JUPITER_ISLAND', name: 'Jupiter Island', lat: 27.0270, lng: -80.0980, type: 'beach', tags: 'ciudad barrio zona area city town isla yupiter' },
  { id: 'LOC_GABLES_ESTATES', name: 'Gables Estates', lat: 25.6650, lng: -80.2620, type: 'residence', tags: 'ciudad barrio zona area city town mansion privada exclusividad' },

  // ─── 📍 CIUDADES, BARRIOS Y ZONAS COMUNES ───
  { id: 'LOC_SOBE_AREA', name: 'South Beach (Área General)', lat: 25.7826, lng: -80.1341, type: 'beach', tags: 'ciudad barrio zona area city town playa mar sobe ocean drive' },
  { id: 'LOC_MID_BEACH', name: 'Mid-Beach (Miami Beach)', lat: 25.8175, lng: -80.1230, type: 'beach', tags: 'ciudad barrio zona area city town playa mar' },
  { id: 'LOC_NORTH_BEACH', name: 'North Beach (Miami Beach)', lat: 25.8643, lng: -80.1215, type: 'beach', tags: 'ciudad barrio zona area city town playa mar' },
  { id: 'LOC_BRICKELL_AREA', name: 'Brickell (Área General)', lat: 25.7583, lng: -80.1915, type: 'business', tags: 'ciudad barrio zona area city town brikell brikel financiero' },
  { id: 'LOC_DOWNTOWN', name: 'Downtown Miami (Área General)', lat: 25.7743, lng: -80.1937, type: 'business', tags: 'ciudad barrio zona area city town centro dntwn' },
  { id: 'LOC_EDGEWATER', name: 'Edgewater', lat: 25.8021, lng: -80.1888, type: 'business', tags: 'ciudad barrio zona area city town ewater' },
  { id: 'LOC_WYNWOOD', name: 'Wynwood', lat: 25.8042, lng: -80.1998, type: 'business', tags: 'ciudad barrio zona area city town winwud' },
  { id: 'LOC_DESIGN_DISTRICT', name: 'Design District', lat: 25.8130, lng: -80.1933, type: 'business', tags: 'ciudad barrio zona area city town distrito diseno' },
  { id: 'LOC_LITTLE_HAVANA', name: 'Little Havana', lat: 25.7650, lng: -80.2150, type: 'business', tags: 'ciudad barrio zona area city town habana calle ocho' },
  { id: 'LOC_CORAL_GABLES', name: 'Coral Gables', lat: 25.7215, lng: -80.2684, type: 'business', tags: 'ciudad barrio zona area city town coral geibols' },
  { id: 'LOC_COCONUT_GROVE', name: 'Coconut Grove', lat: 25.7123, lng: -80.2546, type: 'business', tags: 'ciudad barrio zona area city town coco grov' },
  { id: 'LOC_KEY_BISCAYNE', name: 'Key Biscayne', lat: 25.6937, lng: -80.1627, type: 'beach', tags: 'ciudad barrio zona area city town isla cayo viscayn' },
  { id: 'LOC_DORAL', name: 'Doral', lat: 25.8195, lng: -80.3553, type: 'business', tags: 'ciudad barrio zona area city town el doral' },
  { id: 'LOC_KENDALL', name: 'Kendall', lat: 25.6793, lng: -80.3172, type: 'business', tags: 'ciudad barrio zona area city town kendal' },
  { id: 'LOC_SOUTH_MIAMI', name: 'South Miami', lat: 25.7075, lng: -80.2933, type: 'business', tags: 'ciudad barrio zona area city town sur miami somi' },
  { id: 'LOC_PINECREST', name: 'Pinecrest', lat: 25.6660, lng: -80.3060, type: 'business', tags: 'ciudad barrio zona area city town' },
  { id: 'LOC_PALMETTO_BAY', name: 'Palmetto Bay', lat: 25.6200, lng: -80.3250, type: 'business', tags: 'ciudad barrio zona area city town palmeto' },
  { id: 'LOC_CUTLER_BAY', name: 'Cutler Bay', lat: 25.5800, lng: -80.3450, type: 'business', tags: 'ciudad barrio zona area city town cutler' },
  { id: 'LOC_HOMESTEAD', name: 'Homestead', lat: 25.4687, lng: -80.4776, type: 'business', tags: 'ciudad barrio zona area city town jomsted' },
  { id: 'LOC_MIAMI_LAKES', name: 'Miami Lakes', lat: 25.9120, lng: -80.3150, type: 'business', tags: 'ciudad barrio zona area city town lagos' },
  { id: 'LOC_HIALEAH', name: 'Hialeah', lat: 25.8670, lng: -80.2900, type: 'business', tags: 'ciudad barrio zona area city town jialea' },
  { id: 'LOC_NORTH_MIAMI', name: 'North Miami', lat: 25.8900, lng: -80.1850, type: 'business', tags: 'ciudad barrio zona area city town nmb' },
  { id: 'LOC_AVENTURA', name: 'Aventura', lat: 25.9565, lng: -80.1392, type: 'business', tags: 'ciudad barrio zona area city town' },
  { id: 'LOC_SUNNY_ISLES', name: 'Sunny Isles Beach', lat: 25.9429, lng: -80.1234, type: 'beach', tags: 'ciudad barrio zona area city town sani ails' },
  { id: 'LOC_BAL_HARBOUR', name: 'Bal Harbour', lat: 25.8926, lng: -80.1245, type: 'beach', tags: 'ciudad barrio zona area city town val jarbor balharbour' },
  { id: 'LOC_SURFSIDE', name: 'Surfside', lat: 25.8773, lng: -80.1223, type: 'beach', tags: 'ciudad barrio zona area city town surf' },
  { id: 'LOC_HOLLYWOOD', name: 'Hollywood', lat: 26.0112, lng: -80.1495, type: 'business', tags: 'ciudad barrio zona area city town joliwud holiwud' },
  { id: 'LOC_HALLANDALE', name: 'Hallandale Beach', lat: 25.9850, lng: -80.1450, type: 'business', tags: 'ciudad barrio zona area city town jalandel' },
  { id: 'LOC_PEMBROKE_PINES', name: 'Pembroke Pines', lat: 26.0070, lng: -80.2950, type: 'business', tags: 'ciudad barrio zona area city town penbrok' },
  { id: 'LOC_MIRAMAR', name: 'Miramar', lat: 25.9770, lng: -80.2900, type: 'business', tags: 'ciudad barrio zona area city town' },
  { id: 'LOC_WESTON', name: 'Weston', lat: 26.1004, lng: -80.3998, type: 'business', tags: 'ciudad barrio zona area city town' },
  { id: 'LOC_PLANTATION', name: 'Plantation', lat: 26.1275, lng: -80.2330, type: 'business', tags: 'ciudad barrio zona area city town plantacion' },
  { id: 'LOC_FORT_LAUDERDALE', name: 'Fort Lauderdale', lat: 26.1224, lng: -80.1373, type: 'business', tags: 'ciudad barrio zona area city town ft lauderdale for lodordel' },
  { id: 'LOC_CORAL_SPRINGS', name: 'Coral Springs', lat: 26.2713, lng: -80.2706, type: 'business', tags: 'ciudad barrio zona area city town' },
  { id: 'LOC_PARKLAND', name: 'Parkland', lat: 26.3101, lng: -80.2373, type: 'business', tags: 'ciudad barrio zona area city town' },
  { id: 'LOC_POMPANO', name: 'Pompano Beach', lat: 26.2375, lng: -80.1250, type: 'beach', tags: 'ciudad barrio zona area city town playa' },
  { id: 'LOC_DEERFIELD', name: 'Deerfield Beach', lat: 26.3180, lng: -80.0990, type: 'beach', tags: 'ciudad barrio zona area city town dirfield' },
  { id: 'LOC_BOCA_RATON', name: 'Boca Raton', lat: 26.3587, lng: -80.0831, type: 'business', tags: 'ciudad barrio zona area city town voca raton' },
  { id: 'LOC_BOCA_WEST', name: 'Boca West', lat: 26.3750, lng: -80.1550, type: 'business', tags: 'ciudad barrio zona area city town voca oeste country club' },
  { id: 'LOC_DELRAY', name: 'Delray Beach', lat: 26.4610, lng: -80.0720, type: 'beach', tags: 'ciudad barrio zona area city town del rei' },
  { id: 'LOC_BOYNTON', name: 'Boynton Beach', lat: 26.5250, lng: -80.0660, type: 'beach', tags: 'ciudad barrio zona area city town bointon' },
  { id: 'LOC_WELLINGTON', name: 'Wellington', lat: 26.6580, lng: -80.2580, type: 'business', tags: 'ciudad barrio zona area city town welinton' },
  { id: 'LOC_WEST_PALM', name: 'West Palm Beach', lat: 26.7153, lng: -80.0534, type: 'business', tags: 'ciudad barrio zona area city town wpb oeste palma' },
  { id: 'LOC_PALM_BEACH', name: 'Palm Beach (Isla)', lat: 26.7056, lng: -80.0364, type: 'beach', tags: 'ciudad barrio zona area city town isla palma pb' },
  { id: 'LOC_SINGER_ISLAND', name: 'Singer Island', lat: 26.7875, lng: -80.0350, type: 'beach', tags: 'ciudad barrio zona area city town isla cantante wpb' },
  { id: 'LOC_JUPITER', name: 'Jupiter', lat: 26.9340, lng: -80.0940, type: 'beach', tags: 'ciudad barrio zona area city town yupiter' },
  { id: 'LOC_NAPLES', name: 'Naples', lat: 26.1420, lng: -81.7948, type: 'beach', tags: 'ciudad barrio zona area city town napoles costa oeste' },
  { id: 'LOC_MARCO_ISLAND', name: 'Marco Island', lat: 25.9360, lng: -81.7150, type: 'beach', tags: 'ciudad barrio zona area city town isla marco' },
  { id: 'LOC_KEY_LARGO', name: 'Key Largo', lat: 25.0860, lng: -80.4470, type: 'beach', tags: 'ciudad barrio zona area city town cayo largo' },
  { id: 'LOC_ISLAMORADA', name: 'Islamorada', lat: 24.9240, lng: -80.6270, type: 'beach', tags: 'ciudad barrio zona area city town isla morada' },
  { id: 'LOC_MARATHON', name: 'Marathon', lat: 24.7130, lng: -81.0900, type: 'beach', tags: 'ciudad barrio zona area city town maraton cayos' },
  { id: 'LOC_KEY_WEST', name: 'Key West', lat: 24.5551, lng: -81.7800, type: 'beach', tags: 'ciudad barrio zona area city town cayo hueso oeste' },
  { id: 'LOC_ORLANDO_DISNEY', name: 'Orlando - Walt Disney World', lat: 28.3772, lng: -81.5707, type: 'park', tags: 'ciudad barrio zona area city town parque atraccion magia mikey disnei' },
  { id: 'LOC_ORLANDO_UNIVERSAL', name: 'Orlando - Universal Studios', lat: 28.4743, lng: -81.4678, type: 'park', tags: 'ciudad barrio zona area city town parque atraccion estudios' }
];